# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages:
  - commit

default_language_version:
  python: python3.11

exclude: /migrations/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        stages:
          - commit
      - id: double-quote-string-fixer
        stages:
          - commit
      - id: end-of-file-fixer
        exclude: \.svg$
        stages:
          - commit

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      entry: mypy
      pass_filenames: true
      args: [ --follow-imports=silent, --config=setup.cfg ]
      additional_dependencies:
       - types-croniter==1.0.2
       - types-dateparser==1.0.7
       - types-freezegun==1.1.2
       - types-python-dateutil==2.8.2
       - types-pytz==2021.3.0
       - types-requests==2.25.11

  - repo: https://github.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        args: [--config, setup.cfg]
        additional_dependencies:
          [
            flake8-isort==5.0.3,
            flake8-blind-except==0.2.1,
            flake8-broken-line==0.6.0,
            flake8-bugbear==22.10.27,
            flake8-builtins==2.0.1,
            flake8-class-attributes-order==0.1.3,
            flake8-cognitive-complexity==0.1.0,
            flake8-commas==2.1.0,
            flake8-comprehensions==3.10.1,
            flake8-debugger==4.1.2,
            flake8-eradicate==1.4.0,
            flake8-functions==0.0.7,
            flake8-isort==5.0.3,
            flake8-mutable==1.2.0,
            flake8-print==5.0.0,
            flake8-pytest==1.4,
            flake8-pytest-style==1.6.0,
            flake8-quotes==3.3.1,
            flake8-string-format==0.3.0,
            flake8-variables-names==0.0.5,
            flake8-isort==5.0.3,
          ]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
      - id: absolufy-imports

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: python
        args: ["--profile", "black", --line-length=119]
