version: '3.9'

services:

  db:
    image: postgres:14.5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    image: redis:7.0.5
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    depends_on:
      - db
    env_file:
      - ./.env

  web:
    build: .
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn --host 0.0.0.0 main:app"
    restart: always
    volumes:
      - media_value:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    env_file:
      - ./.env
    restart: always
    depends_on:
      - web

volumes:
  postgres_data:
  media_value:
